// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSPi.Infrastructure.Persistence;

#nullable disable

namespace OSPi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OSPiDbContext))]
    partial class OSPiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("OSPi.Domain.Entities.ControllerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LocationLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("LocationLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("RainDelayUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SequentialDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseWeather")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaterLevelPercent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ControllerSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SequentialDefault = true,
                            StationDelaySeconds = 0,
                            UseWeather = true,
                            WaterLevelPercent = 100
                        });
                });

            modelBuilder.Entity("OSPi.Domain.Entities.MasterStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MasterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffAdjustSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnAdjustSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MasterIndex")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("MasterStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MasterIndex = 1,
                            OffAdjustSeconds = 0,
                            OnAdjustSeconds = 0
                        },
                        new
                        {
                            Id = 2,
                            MasterIndex = 2,
                            OffAdjustSeconds = 0,
                            OnAdjustSeconds = 0
                        });
                });

            modelBuilder.Entity("OSPi.Domain.Entities.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DateRangeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DateRangeEndDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DateRangeEndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DateRangeStartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DateRangeStartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalRemainder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlyDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("OddEven")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepeatCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepeatEveryMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("SingleRunDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartTimeType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseWeather")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("WeekdayMask")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("OSPi.Domain.Entities.ProgramZoneDuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.HasIndex("ProgramId", "ZoneId")
                        .IsUnique();

                    b.ToTable("ProgramZoneDurations");
                });

            modelBuilder.Entity("OSPi.Domain.Entities.RunLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ZoneId");

                    b.ToTable("RunLog");
                });

            modelBuilder.Entity("OSPi.Domain.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BoundToMaster1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BoundToMaster2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HardwareBit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreRain")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreSensor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HardwareBit")
                        .IsUnique();

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 0,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 1"
                        },
                        new
                        {
                            Id = 2,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 1,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 2"
                        },
                        new
                        {
                            Id = 3,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 2,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 3"
                        },
                        new
                        {
                            Id = 4,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 3,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 4"
                        },
                        new
                        {
                            Id = 5,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 4,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 5"
                        },
                        new
                        {
                            Id = 6,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 5,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 6"
                        },
                        new
                        {
                            Id = 7,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 6,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 7"
                        },
                        new
                        {
                            Id = 8,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 7,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 8"
                        },
                        new
                        {
                            Id = 9,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 8,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 9"
                        },
                        new
                        {
                            Id = 10,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 9,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 10"
                        },
                        new
                        {
                            Id = 11,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 10,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 11"
                        },
                        new
                        {
                            Id = 12,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 11,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 12"
                        },
                        new
                        {
                            Id = 13,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 12,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 13"
                        },
                        new
                        {
                            Id = 14,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 13,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 14"
                        },
                        new
                        {
                            Id = 15,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 14,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 15"
                        },
                        new
                        {
                            Id = 16,
                            BoundToMaster1 = false,
                            BoundToMaster2 = false,
                            Disabled = false,
                            Group = 0,
                            HardwareBit = 15,
                            IgnoreRain = false,
                            IgnoreSensor = false,
                            Name = "Zone 16"
                        });
                });

            modelBuilder.Entity("OSPi.Domain.Entities.MasterStation", b =>
                {
                    b.HasOne("OSPi.Domain.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("OSPi.Domain.Entities.Program", b =>
                {
                    b.OwnsMany("OSPi.Domain.Entities.ProgramStartTime", "StartTimes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Kind")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ProgramId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Slot")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("ProgramId");

                            b1.ToTable("ProgramStartTimes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProgramId");
                        });

                    b.Navigation("StartTimes");
                });

            modelBuilder.Entity("OSPi.Domain.Entities.ProgramZoneDuration", b =>
                {
                    b.HasOne("OSPi.Domain.Entities.Program", "Program")
                        .WithMany("ZoneDurations")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPi.Domain.Entities.Zone", "Zone")
                        .WithMany("ProgramDurations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("OSPi.Domain.Entities.RunLogEntry", b =>
                {
                    b.HasOne("OSPi.Domain.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OSPi.Domain.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("OSPi.Domain.Entities.Program", b =>
                {
                    b.Navigation("ZoneDurations");
                });

            modelBuilder.Entity("OSPi.Domain.Entities.Zone", b =>
                {
                    b.Navigation("ProgramDurations");
                });
#pragma warning restore 612, 618
        }
    }
}
